//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Controls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.controls_Grab;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad
        {
            get
            {
                return SteamVR_Actions.controls_Touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean CreatePoint
        {
            get
            {
                return SteamVR_Actions.controls_CreatePoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeletePoint
        {
            get
            {
                return SteamVR_Actions.controls_DeletePoint;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.controls_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.controls_Haptics;
            }
        }
    }
}
